{{- if and .Values.gateway.enabled .Values.gateway.createGateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.app.name }}-gateway
  namespace: {{ include "my-app-chart.namespace" . }}
  labels:
    app: {{ .Values.app.name }}
  {{- with .Values.gateway.gatewayAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
  {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode }}
        {{- if .tls.certificateRefs }}
        certificateRefs:
        {{- range .tls.certificateRefs }}
          - name: {{ .name }}
            kind: {{ .kind | default "Secret" }}
            {{- if .namespace }}
            namespace: {{ .namespace }}
            {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: {{ .allowedRoutes.namespaces.from | default "Same" }}
  {{- end }}
{{- end }}