{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.app.name }}-httproute
  namespace: {{ include "my-app-chart.namespace" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
  {{- with .Values.gateway.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- else if .Values.gateway.hostnames }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ index .Values.gateway.hostnames 0 | quote }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  {{- end }}
spec:
  parentRefs:
  {{- if eq .Values.gateway.mode "dedicated" }}
    - name: {{ .Values.app.name }}-gateway
      namespace: {{ include "my-app-chart.namespace" . }}
  {{- else }}
    {{- if .Values.gateway.sharedGateway }}
    - name: {{ .Values.gateway.sharedGateway.name }}
      namespace: {{ .Values.gateway.sharedGateway.namespace }}
    {{- else }}
    {{- fail "sharedGateway must be defined when gateway.mode is 'shared'" -}}
    {{- end }}
  {{- end }}
  hostnames:
  {{- range .Values.gateway.hostnames }}
    - {{ . | quote }}
  {{- end }}
  rules:
  {{- range .Values.gateway.routes }}
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path | quote }}
      backendRefs:
        - name: {{ $.Values.app.name }}
          port: {{ .backendPort | default $.Values.service.port }}
          weight: {{ .weight | default 1 }}
  {{- end }}
{{- end }}
