{{- if .Values.vaultStaticSecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.vaultStaticSecret.name | default (printf "%s-secret" .Values.app.name) }}
  namespace: {{ .Values.vaultStaticSecret.namespace | default (printf "%s-%s" .Values.namespace.name .Values.environment) }}
spec:
  vaultAuthRef: {{ .Values.vaultStaticSecret.vaultAuthRef | default "vault-auth" }}
  mount: {{ .Values.vaultStaticSecret.mount | default "kv" }}
  type: {{ .Values.vaultStaticSecret.type | default "kv-v2" }}
  path: {{ .Values.vaultStaticSecret.path | default (printf "%s/apps/%s" .Values.environment .Values.app.name) }}
  destination:
    name: {{ if .Values.vaultStaticSecret.destination }}{{ .Values.vaultStaticSecret.destination.name | default .Values.app.name }}{{ else }}{{ .Values.app.name }}{{ end }}
    create: {{ if .Values.vaultStaticSecret.destination }}{{ .Values.vaultStaticSecret.destination.create | default true }}{{ else }}true{{ end }}
{{- end }}
