{{- if .Values.secrets.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.secrets.vault.destination.name | default (printf "%s-secret" .Values.app.name) }}
  namespace: {{ include "my-app-chart.namespace" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.secrets.vault.authRef }}
  mount: {{ .Values.secrets.vault.mount }}
  type: {{ .Values.secrets.vault.type | default "kv-v2" }}
  path: {{ .Values.secrets.vault.path }}
  destination:
    name: {{ .Values.secrets.vault.destination.name }}
    create: {{ .Values.secrets.vault.destination.create | default true }}
{{- end }}
