{{- if .Values.vaultStaticSecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.vaultStaticSecret.name | default (printf "%s-secret" .Values.app.name) }}
  namespace: {{ .Values.vaultStaticSecret.namespace | default .Values.namespace.name }}
spec:
  vaultAuthRef: {{ .Values.vaultStaticSecret.vaultAuthRef | default "vault-auth" }}
  mount: {{ .Values.vaultStaticSecret.mount | default "kv" }}
  type: {{ .Values.vaultStaticSecret.type | default "kv-v2" }}
  path: {{ .Values.vaultStaticSecret.path | default (printf "%s/apps/%s" .Values.environment .Values.app.name) }}
  destination:
    name: {{ .Values.vaultStaticSecret.destination.name | default .Values.app.name }}
    create: {{ .Values.vaultStaticSecret.destination.create | default true }}
{{- end }}
